// src/renderer/main-content/task-table/row-types/cell-types/ExternalCell.vue
<template>
    <td class="external-link-cell">
        <span
            title="Gamer Escape"
            @click="gotoGamerEscape()"
        >
            <img
                src="../../../../assets/gamerescape.png"
                alt="Gamer Escape"
                height="20"
                width="20"
            >
        </span>
        <span
            title="Garland Tools"
            @click="gotoGarlandTools()"
        >
            <img
                src="../../../../assets/Garland.png"
                alt="Garland Tools"
                height="20"
                width="20"
            >
        </span>
    </td>
</template>

<script>
    const { shell } = require('electron');

    export default {
        name: 'external-data',
        props: {
            taskName: String
        },
        methods: {
            gotoGamerEscape: function () {
                shell.openExternal('https://ffxiv.gamerescape.com/wiki/' + this.taskName.replace(/ /g, '_'));
            },
            gotoGarlandTools: function () {
                shell.openExternal('https://www.garlandtools.org/db/#search/' + this.taskName.replace(/ /g, '%20'));
            }
        }
    };
</script>

<style>
    .external-link-cell {
        width: 45px;
    }

    .external-link-cell img {
        cursor: pointer;
    }
</style>

// src/app/core/components/task-table/cell/external/external-cell.component.ts
import { Component, Input } from '@angular/core';
import { shell } from '@electron/remote';

import { Task } from '../../../../../domain/Task';

@Component({
    selector: 'xiv-external-cell',
    templateUrl: './external-cell.component.html',
    styleUrls: ['./external-cell.component.scss']
})
export class ExternalCellComponent {
    @Input() task: Task;

    gotoGamerEscape() {
        let name = this.task.name.replace(/ /g, '_');
        name = gamerEscapeSafeMap(name);

        shell.openExternal(`https://ffxiv.gamerescape.com/wiki/${name}`);
    }

    gotoGarlandTools() {
        const name = this.task.name.replace(/ /g, '%20');
        shell.openExternal(`https://www.garlandtools.org/db/#search/${name}`);
    }
}

function gamerEscapeSafeMap(name) {
    const match = (n, id) => this.task.name === n && this.task.id === id;

    if(match('Mending Fences', 143)) return `${name}_(Levequest)`;

    return name;
}

<td class="external-link-cell noSelect">
    <span
        title="Gamer Escape"
        (click)="gotoGamerEscape()"
    >
        <img
            src="../../../../../../assets/icons/gamerescape.png"
            alt="Gamer Escape"
            height="20"
            width="20"
        >
    </span>
    <span
        title="Garland Tools"
        (click)="gotoGarlandTools()"
    >
        <img
            src="../../../../../../assets/icons/garland.png"
            alt="Garland Tools"
            height="20"
            width="20"
        >
    </span>
</td>
