// src/renderer/main-content/nav-drawer/NavGroup.vue
<template>
    <div
        class="nav-group"
        ref="container"
        :style="{ height }"
        :class="{ collapsed: !show }"
    >
        <div
            class="nav-bar-button"
            @click="selectGroup(degree)"
            :title="group.name"
            :style="buttonStyle"
        >
            {{group.name}}
        </div>

        <template v-if="group.subGroups">
            <nav-group
                v-for="subGroup in group.subGroups"
                :key="subGroup.name"
                :show="showChildren"
                :degree="degree + 1"
                :group="subGroup"
            />
        </template>
    </div>
</template>

<script>
    import { mapState } from 'vuex';

    export default {
        name: 'nav-group',
        props: {
            show: Boolean,
            degree: Number,
            group: Object,
        },
        data: () => ({
            height: '',
            timeout: null
        }),
        methods: {
            selectGroup: function(degree) {
                if(this.group.onNavigation) {
                    this.group.onNavigation(this.$store);
                }
                else {
                    this.$store.commit('navigation/SET_CRUMB_AT', {
                        groupName: this.group.name,
                        degree
                    });

                    this.$store.commit('navigation/SET_SELECTED_GROUP', this.group);
                }
            }
        },
        computed: {
            ...mapState('navigation', {
                breadcrumbs: 'breadcrumbs'
            }),
            showChildren: function() {
                return this.breadcrumbs[this.degree] === this.group.name;
            },
            buttonStyle: function() {
                const degMod = (this.degree + 4);
                const opacity = degMod >= 10 ? 1 : `0.${degMod}`;

                return {
                    'background-color': `rgba(0, 0, 0, ${opacity})`,
                    'padding-left': `${(this.degree * 5) + 5}px`
                };
            }
        },
        watch: {
            show: function(newShow, oldShow) {
                this.height = `${this.$refs.container.scrollHeight}px`;
                clearTimeout(this.timeout);

                this.$nextTick(() => {
                    this.timeout = setTimeout(() => {
                        this.height = oldShow ? "0px" : "";
                    }, oldShow ? 0 : 500);
                });
            }
        }
    }
</script>

<style lang="scss">
@import '../../../styles/colors';

.nav-group {
    transition: height 0.5s ease;

    &.collapsed {
        height: 0;
        overflow: hidden;
    }

    .nav-bar-button {
        background-color: $blue-3;
        border-top: 2px solid black;
        height: 30px;
        line-height: 30px;
        padding: 0 5px;
        user-select: none;

        &:hover {
            filter: brightness(150%);
            cursor: pointer;
        }

        &:active {
            filter: brightness(50%);
        }
    }
}
</style>

// src/app/core/component/nav-drawer/nav-group/nav-group.component.ts
import { Component, Input, OnChanges, OnInit, SimpleChanges, ViewChild } from '@angular/core';

import { DataGroup } from '@domain/DataGroup';

import { NavigationService } from '@service/navigation/navigation.service';

@Component({
    selector: 'xiv-nav-group',
    templateUrl: './nav-group.component.html',
    styleUrls: ['./nav-group.component.scss']
})
export class NavGroupComponent implements OnInit, OnChanges {
    @Input() show: boolean;
    @Input() degree: number;
    @Input() group: DataGroup;

    @ViewChild('container') container;

    height = '';
    timeout = null;

    showChildren: boolean = false;
    buttonStyle;

    constructor(private svcNavigation: NavigationService) {
    }

    ngOnInit() {
        this.svcNavigation.breadcrumbs$.subscribe((breadcrumbs) => {
            this.showChildren = breadcrumbs[this.degree] === this.group.name;

            // Calculate group style
            const degMod = (this.degree + 4);
            const opacity = degMod >= 10 ? 1 : `0.${degMod}`;

            this.buttonStyle = {
                'background-color': `rgba(0, 0, 0, ${opacity})`,
                'padding-left': `${(this.degree * 5) + 5}px`
            };
        });
    }

    ngOnChanges(changes: SimpleChanges) {
        if(changes.show) {
            this.height = `${this.container.scrollHeight}px`;
            clearTimeout(this.timeout);

            this.timeout = setTimeout(() => {
                this.height = changes.show.previousValue ? '0px' : '';
            }, changes.show.previousValue ? 0 : 500);
        }
    }

    selectGroup(degree) {
        this.svcNavigation.setCrumbAt(degree, this.group.name);
        this.svcNavigation.setSelectedGroup(this.group);
    }
}

<div
    #container
    class="nav-group"
    [style.height]="height"
    [ngClass]="{ collapsed: !show }"
>
    <div
        class="nav-bar-button"
        (click)="selectGroup(degree)"
        [title]="group.name"
        [style]="buttonStyle"
    >
        {{group.name}}
    </div>

    <template *ngIf="group.subGroups">
        <xiv-nav-group
            *ngFor="let subGroup in group.subGroups"
            [show]="showChildren"
            [degree]="degree + 1"
            [group]="subGroup"
        ></xiv-nav-group>
    </template>
</div>
