// src/renderer/components/task-table/TaskTable.vue
<template>
    <div v-if="!!columnConfig" class="task-table-container">
        <div class="task-table-toolbar">
            <span v-if="hasTasks && !group.isNumericCompletion">
                <quick-mark-dropdown :filtered-tasks="filteredTasks"/>
            </span>

            <span v-if="hasTasks && !group.isNumericCompletion">
                <selection-action-dropdown
                    :group="group"
                    :filtered-tasks="filteredTasks"
                    v-on:select-change="onSelectChange"
                />
            </span>

            <span v-if="hasTasks">
                <chain-dropdown></chain-dropdown>
            </span>

            <span v-if="group.isCustomGroup">
                <custom-task-dropdown :filtered-tasks="filteredTasks"/>
            </span>

            <span v-if="hasTasks" class="row-count" :title="(totalTasks - displayedTasks) + ' Hidden'">
                {{displayedTasks}} Rows displayed
            </span>
        </div>

        <div class="task-table-scroll-container" ref="taskTable">
            <table class="xiv-table" v-if="hasTasks">
                <task-table-header
                    @filter-change="onFilterChange"
                    :column-config="columnConfig"
                    :uniqueValues="uniqueValues"
                    :is-numeric-completion="group.isNumericCompletion"
                />
                <task-table-data-row
                    :key="rerenderKey"
                    :column-config="columnConfig"
                    :enable-drag="group.draggable"
                    :tasks="filteredTasks"
                />
            </table>
        </div>
    </div>
</template>

<script>
    import { eStore } from "../../../store/electronStore";

    // Components
    import QuickMarkDropdown from './QuickMarkDropdown';
    import SelectionActionDropdown from "./SelectionActionDropdown";
    import ChainDropdown from "./ChainDropdown";
    import CustomTaskDropdown from './CustomTaskDropdown';
    import TaskTableHeader from './row-types/TaskTableHeader';
    import TaskTableDataRow from './row-types/TaskTableDataRow';

    // Export component
    export default {
        name: 'task-table',
        components: {
            QuickMarkDropdown,
            SelectionActionDropdown,
            ChainDropdown,
            CustomTaskDropdown,
            TaskTableHeader,
            TaskTableDataRow,
        },
        props: {
            columnConfig: Array,
            group: Object,
            tasks: Object,
        },
        data: () => ({
            filters: {
                completion: {
                    completed: eStore.get("table-filters.completed"),
                    incomplete: eStore.get("table-filters.incomplete"),
                    excluded: eStore.get("table-filters.excluded"),
                }
            },
            displayedTasks: 0,
            totalTasks: 0,
            rerenderKey: 0
        }),
        computed: {
            hasTasks: function() {
                return this.tasks && Object.keys(this.tasks).length > 0;
            },
            uniqueValues: function() {
                const uniqueValues = {};

                // Grab unique values from the filtered task list
                for(const id in this.filteredTasks) {
                    const task = this.filteredTasks[id];

                    this.columnConfig.forEach(({ key }) => {
                        if(!uniqueValues[key]) uniqueValues[key] = [];

                        const value = !task[key] && task[key] !== 0 ? "" : task[key];
                        if(uniqueValues[key].indexOf(value) === -1) {
                            uniqueValues[key].push(value);
                        }
                    });
                }

                // Sort the unique values for pretty filter dropdowns
                this.columnConfig.forEach((column) => {
                    if(!uniqueValues[column.key]) return;
                    if(column.filterType === 'number') {
                        uniqueValues[column.key].sort((a, b) => parseInt(a) - parseInt(b));
                    }
                    else {
                        uniqueValues[column.key].sort();
                    }
                });

                return uniqueValues;
            },
            filteredTasks: function() {
                let filtered = Object.assign({}, this.tasks);
                const hotwire = this.group.isNumericCompletion ? [] : [{ key: 'completion' }];
                hotwire.push(...this.columnConfig);

                for(const { key } of hotwire) {
                    const filter = this.filters[key];

                    if(filter) {
                        for(const id in filtered) {
                            let removeFromFiltered = false;

                            // Completion filters
                            if(key === 'completion') {
                                switch(this.tasks[id].completionFlag) {
                                    case "Y": removeFromFiltered = !filter.completed; break;
                                    case "N": removeFromFiltered = !filter.incomplete; break;
                                    case "X": removeFromFiltered = !filter.excluded; break;
                                    default: removeFromFiltered = !filter.incomplete; break;
                                }
                            }
                            // Blank value search
                            else if(filter.value === 'Blank') {
                                removeFromFiltered = !!filtered[id][key];
                            }
                            // Column value fuzzy search filter
                            else {
                                let safeValue = filtered[id][key];
                                if(safeValue === null || safeValue === undefined) safeValue = '';

                                const columnValue = safeValue.toString().toLowerCase();
                                removeFromFiltered = !columnValue.includes(filter.value.toLowerCase());
                            }

                            if(removeFromFiltered) {
                                delete filtered[id];
                            }
                        }
                    }
                }

                this.displayedTasks = Object.keys(filtered).length;
                this.totalTasks = Object.keys(this.tasks).length;

                return filtered;
            }
        },
        methods: {
            onFilterChange: function(filters) {
                this.filters = filters;
            },
            onSelectChange: function() {
                this.rerenderKey++;
            }
        },
        watch: {
            group: function(oldGroup, newGroup) {
                if(newGroup && oldGroup.name !== newGroup.name) {
                    this.$refs.taskTable.scrollTop = 0;
                }
            }
        }
    }
</script>

<style lang="scss">
.task-table-container {
    display: flex;
    flex-direction: column;
}

.task-table-toolbar {
    & > span {
        display: inline-block;
    }

    .row-count {
        margin-left: 5px;
        cursor: default;
    }
}

.task-table-scroll-container {
    display: inline-block;
    overflow-y: auto;

    height: 100%;
    width: 100%;
}
</style>

// src/app/core/component/task-table/task-table.component.ts
import { Component, Input, OnChanges, SimpleChanges } from '@angular/core';

import { Completion } from '@constant';
import { DataGroup } from '@domain/DataGroup';
import { Column } from '@domain/Column';
import { Task } from '@domain/Task';
import { ConfigStoreService } from '@service/store/config-store.service';
import { SaveStoreService } from '@service/store/save-store.service';

@Component({
    selector: 'xiv-task-table',
    templateUrl: 'task-table.component.html',
    styleUrls: ['./task-table.component.scss']
})
export class TaskTableComponent implements OnChanges {
    @Input() columns: Column[];
    @Input() group: DataGroup;
    @Input() tasks: { [key: string]: Task };
    @Input() groupRows: boolean;

    debounceDrag: boolean;
    displayedTasks = 0;
    totalTasks = 0;

    hasTasks: boolean;
    uniqueValues: any;
    filteredTasks: { [key: string]: Task };
    filteredTasksArr: Task[];

    filters = {
        completion: {}
    };

    constructor(private svcSaveStore: SaveStoreService) {
        this.filters.completion = ConfigStoreService.get('table-filters');
    }

    ngOnChanges(changes: SimpleChanges) {
        const { columns, group, tasks } = changes;

        if(tasks) this.hasTasks = this._hasTasks;

        if(columns || group || tasks) {
            this.updateFilteredTasks();
        }
    }

    updateFilteredTasks() {
        this.filteredTasks = this._filteredTasks;
        this.filteredTasksArr = Object.values(this.filteredTasks);
        this.uniqueValues = this._uniqueValues;
    }

    onFilterChange(filters) {
        this.filters = filters;
        this.updateFilteredTasks();
    }

    onRowReorder($event: { dragIndex: number; dropIndex: number }): void {
        // Bail if nothing moved
        if($event.dragIndex === $event.dropIndex) return;

        // Grab original data
        const draggedTask = this.filteredTasksArr[$event.dragIndex];
        const customFlags = this.svcSaveStore.get('overall.custom');
        const customMeta = this.svcSaveStore.get('custom');
        const taskKeys = Object.keys(customMeta);
        const draggedKey = `x${draggedTask.id}`;

        // Insert the dragged task and remove its original
        if($event.dragIndex < $event.dropIndex) {
            taskKeys.splice($event.dropIndex + 1, 0, draggedKey);
            taskKeys.splice($event.dragIndex, 1);
        }
        else {
            taskKeys.splice($event.dropIndex, 0, draggedKey);
            taskKeys.splice($event.dragIndex + 1, 1);
        }

        // Reorder saved
        const newTasks = {}, newFlags = {}, newMeta = {};
        taskKeys.forEach((key) => {
            newTasks[key] = this.tasks[key];
            newFlags[key.substr(1)] = customFlags[key.substr(1)];
            newMeta[key] = customMeta[key];
        });

        // Assign re-ordered objects, save to file
        const firstId = Object.keys(this.tasks)[0];
        this.tasks[firstId]._parent.tasks = newTasks;
        this.svcSaveStore.set('overall.custom', newFlags);
        this.svcSaveStore.set('custom', newMeta);

        // Debounce dragging since its tied to file write
        this.debounceDrag = true;
        setTimeout(() => this.debounceDrag = false, 1000);
    }

    //#region----------------------------------------------------------- Computed
    get _hasTasks() {
        return this.tasks && Object.keys(this.tasks).length > 0;
    }

    get _uniqueValues() {
        const uniqueValues = {};

        // Grab unique values from the filtered task list
        for(const id in this.filteredTasks) {
            if(this.filteredTasks.hasOwnProperty(id)) {
                const task = this.filteredTasks[id];

                this.columns?.forEach(({ key }) => {
                    if(!uniqueValues[key]) uniqueValues[key] = [];

                    const value = !task[key] && task[key] !== 0 ? '' : task[key];
                    if(uniqueValues[key].indexOf(value) === -1) {
                        uniqueValues[key].push(value);
                    }
                });
            }
        }

        // Sort the unique values for pretty filter dropdowns
        this.columns?.forEach((column) => {
            if(!uniqueValues[column.key]) return;
            if(column.filterType === 'number') {
                uniqueValues[column.key].sort((a, b) => parseInt(a, 10) - parseInt(b, 10));
            }
            else {
                uniqueValues[column.key].sort();
            }
        });

        return uniqueValues;
    }

    get _filteredTasks() {
        const filtered = Object.assign({}, this.tasks);
        const hotwire = this.group.isNumericCompletion ? [] : [{ key: 'completion' }];
        hotwire.push(...this.columns);

        for(const { key } of hotwire) {
            const filter = this.filters[key];

            if(filter) {
                for(const id in filtered) {
                    if(filtered.hasOwnProperty(id)) {
                        let removeFromFiltered = false;

                        // Completion filters
                        if(key === 'completion') {
                            switch(this.tasks[id].completionFlag) {
                                case Completion.Y: removeFromFiltered = !filter.completed; break;
                                case Completion.N: removeFromFiltered = !filter.incomplete; break;
                                case Completion.X: removeFromFiltered = !filter.excluded; break;
                                default: removeFromFiltered = !filter.incomplete; break;
                            }
                        }
                        // Blank value search
                        else if(filter.value === 'Blank') {
                            removeFromFiltered = !!filtered[id][key];
                        }
                        // Column value fuzzy search filter
                        else {
                            let safeValue = filtered[id][key];
                            if(safeValue === null || safeValue === undefined) safeValue = '';

                            const columnValue = safeValue.toString().toLowerCase();
                            removeFromFiltered = !columnValue.includes(filter.value.toLowerCase());
                        }

                        if(removeFromFiltered) {
                            delete filtered[id];
                        }
                    }
                }
            }
        }

        this.displayedTasks = Object.keys(filtered).length;
        this.totalTasks = Object.keys(this.tasks).length;

        return filtered;
    }

    //#endregion
}

<div *ngIf="group.columns" class="task-table-container">
    <div class="task-table-toolbar">
        <span class="p-buttonset">
            <ng-container *ngIf="hasTasks && !group._isNumericCompletion">
                <xiv-quick-mark-dropdown
                    [tasks]="filteredTasks"
                    (onMark)="updateFilteredTasks()"
                ></xiv-quick-mark-dropdown>

                <xiv-select-dropdown
                    [group]="group"
                    [tasks]="filteredTasks"
                ></xiv-select-dropdown>
            </ng-container>

            <ng-container *ngIf="hasTasks">
                <xiv-chain-dropdown
                    [disableUndo]="group.isCustomGroup"
                ></xiv-chain-dropdown>
            </ng-container>

            <xiv-custom-task-dropdown
                *ngIf="group.isCustomGroup"
                [tasks]="filteredTasks"
            ></xiv-custom-task-dropdown>
        </span>

        <span
            *ngIf="hasTasks"
            class="row-count"
            tooltipPosition="top"
            pTooltip="{{tasks.length - filteredTasks.length}} Hidden"
        >
            {{filteredTasks.length}} Rows displayed
        </span>
    </div>

    <div class="task-table-scroll-container">
        <!-- TODO: responsive virtual scroll height -->
        <p-table
            *ngIf="hasTasks"
            styleClass="p-datatable-striped"
            dataKey="storageGroup"
            [value]="filteredTasks"

            [rowGroupMode]="groupRows ? 'subheader' : null"
            groupRowsBy="storageGroup"

            [virtualScroll]="groupRows"
            scrollHeight="800px"

            (onRowReorder)="onRowReorder($event)"
        >
            <ng-template pTemplate="header">
                <xiv-header-row
                    [group]="group"
                    [uniqueValues]="uniqueValues"
                    (filterChange)="onFilterChange($event)"
                ></xiv-header-row>
            </ng-template>
            <ng-template pTemplate="groupheader" let-task let-expanded="expanded">
                <tr pRowGroupHeader [pRowToggler]="task">
                    <td>
                        <p-button
                            styleClass="p-button-text p-button-rounded p-button-plain p-mr-2"
                            [icon]="expanded ? 'pi pi-chevron-down' : 'pi pi-chevron-right'"
                        ></p-button>
                    </td>
                    <td [colSpan]="group.columns.length + 1">
                        {{task | groupName}}
                    </td>
                </tr>
            </ng-template>
            <ng-template [pTemplate]="groupRows ? 'rowexpansion' : 'body'" let-task let-rowIndex="rowIndex">
                <xiv-data-row
                    [dragEnabled]="group.draggable && !debounceDrag"
                    [rowIndex]="rowIndex"
                    [columns]="group.columns"
                    [task]="task"
                    (completionChange)="updateFilteredTasks()"
                ></xiv-data-row>
            </ng-template>
        </p-table>
    </div>
</div>
