// src/renderer/main-content/StatBar.vue
<template>
    <div id="stat-bar">
        <summary-line :group="allData" :big="true" />
        <summary-line
            v-if="showSelectedGroupLine"
            :group="selectedGroup"
            :big="true"
        />
    </div>
</template>

<script>
    import { data } from '../../data';
    import { mapState } from 'vuex';
    import SummaryLine from '../components/SummaryLine';

    export default {
        data: () => ({
            allData: data
        }),
        components: {
            'summary-line': SummaryLine
        },
        computed: {
            ...mapState('navigation', {
                selectedGroup: 'selectedGroup'
            }),
            showSelectedGroupLine: function() {
                if(!this.selectedGroup) return false;
                if(this.selectedGroup === this.allData) return false;
                if(this.selectedGroup.percentComplete === undefined) return false;
                if(this.selectedGroup.percentComplete === null) return false;

                return true;
            }
        }
    };
</script>

<style lang="scss">
#stat-bar {
    height: 100px;
    padding: 0 10px;
}
</style>

// src/app/core/component/stat-bar/stat-bar.component.ts
import { Component } from '@angular/core';

import { data } from '@data';
import { NavigationService } from '@service/navigation/navigation.service';

@Component({
    selector: 'xiv-stat-bar',
    templateUrl: './stat-bar.component.html',
    styleUrls: ['./stat-bar.component.scss']
})
export class StatBarComponent {
    allData = data;
    selectedGroup;

    showSelectedGroupLine: boolean = false;

    constructor(private svcNavigation: NavigationService) {
        this.svcNavigation.selectedGroup$.subscribe((selectedGroup) => {
            this.selectedGroup = selectedGroup;

            this.showSelectedGroupLine = this.shouldShowSelectedGroupLine;
        });
    }

    get shouldShowSelectedGroupLine() {
        if(!this.selectedGroup) return false;
        else if(this.selectedGroup === this.allData) return false;
        else if(this.selectedGroup.percentComplete === undefined) return false;
        else if(this.selectedGroup.percentComplete === null) return false;

        return true;
    }
}

<div #statBar class="stat-bar">
    <xiv-summary-line
        *ngIf="!hideOverall"
        [group]="allData"
        [isBig]="true"
    ></xiv-summary-line>

    <xiv-summary-line
        *ngIf="!hideGroup && group?._parent && !group?.isUiGroup"
        [group]="group"
        [isBig]="true"
    ></xiv-summary-line>

    <p-contextMenu
        *ngIf="!!this.group?._parent"
        [target]="statBar"
        [model]="contextMenuItems"
    ></p-contextMenu>
</div>
