// src/app/view/main-menu/patch-notes/dev-notes/dev-notes.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'xiv-dev-notes',
    templateUrl: './dev-notes.component.html',
    styleUrls: ['./dev-notes.component.scss']
})
export class DevNotesComponent {

}

<div class="section">
    <div class="header">Tech Stuff</div>
    <ul>
        <li>Built using Electron</li>
        <li>Powered by Angular</li>
        <li>UI by PrimeNG</li>
    </ul>
</div>

<div class="section">
    <div class="header">Features being considered, planned, or worked on</div>
    <ul>
        <li>Mac Support</li>
        <li>Further translation support</li>
        <li>Armoire section</li>
        <li>Legacy Quests section</li>
        <li>Patch information for every task</li>
        <li>App and/or resource auto-updating</li>
    </ul>
</div>

<div class="section">
    <div class="header">Known Issues</div>
    <ul>
        <li>Tasks that should have been default excluded will not be excluded when app data is corrected</li>
        <li>Scholar & Summoner levels don't chain eachother</li>
        <li>Leve Issue/Start zones are incorrect</li>
        <li>application is not code signed</li>
    </ul>
</div>

// src/renderer/pages/dev-notes.vue
<template>
    <div>
        <h1>Dev Notes</h1>
        <p>An in-app page for transparency on the state of the app</p>

        <br/>

        <h3>Official Release Coming Soon</h3>
        <p>Version 0.5.58 will be the last beta release</p>
        <p>
            The next major version of the app will drop sometime after Endwalker and
            will contain a massive UI overhaul alongside an internal one.
        </p>
        <p>Please look forward to it.</p>

        <br/>

        <h3>Features being considered, planned, or worked on</h3>
        <ul>
            <li>Mac Support</li>
            <li>Further translation support</li>
            <li>Favorites/Pinning for tasks and groups</li>
            <li>Search UX overhaul</li>
            <li>Armoire section</li>
            <li>Customizable themes</li>
            <li>Syncing data available on your character from Lodestone</li>
        </ul>

        <br/>

        <h3>Known Issues</h3>
        <ul>
            <li>Tasks that should have been default excluded will not be excluded when app data is corrected</li>
            <li>Scholar & Summoner levels don't chain eachother</li>
            <li>Leve Issue/Start zones are incorrect</li>
            <li>"Show All Tasks" button laggy for groups with massive data sets</li>
            <li>application is not code signed</li>
        </ul>
    </div>
</template>

<script>
    export default {
        name: 'dev-notes',
    }
</script>
