// src/app/core/components/dropdowns/quick-mark-dropdown/quick-mark-dropdown.component.ts
import { Component, Input } from '@angular/core';
import { StoreService } from '../../../services/store/store.service';

@Component({
    selector: 'xiv-quick-mark-dropdown',
    templateUrl: './quick-mark-dropdown.component.html'
})
export class QuickMarkDropdownComponent {
    @Input() filteredTasks;

    dropdownOpen = false;
    lastChanged = [];

    constructor(private svcStore: StoreService) {
    }

    onChangeTaskCompletion(from, to) {
        this.lastChanged = [];

        let first = true;
        for(const id in this.filteredTasks) {
            if(this.filteredTasks.hasOwnProperty(id)) {
                const task = this.filteredTasks[id];

                if((from === '$' && task.selected) || task.completionFlag === from) {
                    this.lastChanged.push({ task, oldFlag: task.completionFlag });

                    task.changeCompletionFlag(to, first);
                    first = false;
                }
            }
        }

        this.svcStore.applyDataToStore();
    }

    onUndoLastChange() {
        this.lastChanged.forEach((changed, index) => {
            changed.task.changeCompletionFlag(changed.oldFlag, index === 0);
        });

        this.svcStore.applyDataToStore();
        this.lastChanged = [];
    }
}

<div
    class="action-dropdown-container"
    (mouseenter)="dropdownOpen = true"
    (mouseleave)="dropdownOpen = false"
>
    <div class="xiv-dropdown-arrow">
        <icon name="arrow" size="16"></icon>
    </div>
    <div v-if="dropdownOpen" class="xiv-dropdown-body">
        <button
            [disabled]="lastChanged.length === 0"
            class="xiv-dropdown-li"
            (click)="onUndoLastChange()"
        >
            <template *ngIf="lastChanged.length; else noUndo">Undo Last Quick-Mark</template>
            <template #noUndo>Quick-Mark Menu</template>
        </button>
        <button class="xiv-dropdown-li" (click)="onChangeTaskCompletion('N', 'Y')">
            (<icon name="incomplete"></icon> <icon name="arrow"></icon> <icon name="complete"></icon>)
            Mark Incomplete as Complete
        </button>
        <button class="xiv-dropdown-li" (click)="onChangeTaskCompletion('N', 'X')">
            (<icon name="incomplete"></icon> <icon name="arrow"></icon> <icon name="exclude"></icon>)
            Mark Incomplete as Excluded
        </button>
        <button class="xiv-dropdown-li" (click)="onChangeTaskCompletion('Y', 'N')">
            (<icon name="complete"></icon> <icon name="arrow"></icon> <icon name="incomplete"></icon>)
            Mark Complete as Incomplete
        </button>
        <button class="xiv-dropdown-li" (click)="onChangeTaskCompletion('Y', 'X')">
            (<icon name="complete"></icon> <icon name="arrow"></icon> <icon name="exclude"></icon>)
            Mark Complete as Excluded
        </button>
        <button class="xiv-dropdown-li" (click)="onChangeTaskCompletion('X', 'N')">
            (<icon name="exclude"></icon> <icon name="arrow"></icon> <icon name="incomplete"></icon>)
            Mark Excluded as Incomplete
        </button>
        <button class="xiv-dropdown-li" (click)="onChangeTaskCompletion('X', 'Y')">
            (<icon name="exclude"></icon> <icon name="arrow"></icon> <icon name="complete"></icon>)
            Mark Excluded as Complete
        </button>
        <button class="xiv-dropdown-li" (click)="onChangeTaskCompletion('$', 'Y')">
            (<icon name="selected"></icon> <icon name="arrow"></icon> <icon name="complete"></icon>)
            Mark Selected as Complete
        </button>
        <button class="xiv-dropdown-li" (click)="onChangeTaskCompletion('$', 'N')">
            (<icon name="selected"></icon> <icon name="arrow"></icon> <icon name="incomplete"></icon>)
            Mark Selected as Incomplete
        </button>
        <button class="xiv-dropdown-li" (click)="onChangeTaskCompletion('$', 'X')">
            (<icon name="selected"></icon> <icon name="arrow"></icon> <icon name="exclude"></icon>)
            Mark Selected as Excluded
        </button>
    </div>
</div>

// src/renderer/components/task-table/QuickMarkDropdown.vue
<template>
    <div class="action-dropdown-container">
        <div
            class="xiv-dropdown-arrow"
            @mouseenter="dropdownOpen = true"
            @mouseleave="dropdownOpen = false"
        >
            <icon name="arrow" size="16"/>
        </div>
        <div
            class="xiv-dropdown-body"
            v-if="dropdownOpen"
            @mouseenter="dropdownOpen = true"
            @mouseleave="dropdownOpen = false"
        >
            <button :disabled="lastChanged.length === 0" class="xiv-dropdown-li" @click="onUndoLastChange()">
                <template v-if="lastChanged.length">Undo Last Quick-Mark</template>
                <template v-else>Quick-Mark Menu</template>
            </button>
            <button class="xiv-dropdown-li" @click="onChangeTaskCompletion('N', 'Y')">
                (<icon name="incomplete"/> <icon name="arrow"/> <icon name="complete"/>)
                Mark Incomplete as Complete
            </button>
            <button class="xiv-dropdown-li" @click="onChangeTaskCompletion('N', 'X')">
                (<icon name="incomplete"/> <icon name="arrow"/> <icon name="exclude"/>)
                Mark Incomplete as Excluded
            </button>
            <button class="xiv-dropdown-li" @click="onChangeTaskCompletion('Y', 'N')">
                (<icon name="complete"/> <icon name="arrow"/> <icon name="incomplete"/>)
                Mark Complete as Incomplete
            </button>
            <button class="xiv-dropdown-li" @click="onChangeTaskCompletion('Y', 'X')">
                (<icon name="complete"/> <icon name="arrow"/> <icon name="exclude"/>)
                Mark Complete as Excluded
            </button>
            <button class="xiv-dropdown-li" @click="onChangeTaskCompletion('X', 'N')">
                (<icon name="exclude"/> <icon name="arrow"/> <icon name="incomplete"/>)
                Mark Excluded as Incomplete
            </button>
            <button class="xiv-dropdown-li" @click="onChangeTaskCompletion('X', 'Y')">
                (<icon name="exclude"/> <icon name="arrow"/> <icon name="complete"/>)
                Mark Excluded as Complete
            </button>
            <button class="xiv-dropdown-li" @click="onChangeTaskCompletion('$', 'Y')">
                (<icon name="selected"/> <icon name="arrow"/> <icon name="complete"/>)
                Mark Selected as Complete
            </button>
            <button class="xiv-dropdown-li" @click="onChangeTaskCompletion('$', 'N')">
                (<icon name="selected"/> <icon name="arrow"/> <icon name="incomplete"/>)
                Mark Selected as Incomplete
            </button>
            <button class="xiv-dropdown-li" @click="onChangeTaskCompletion('$', 'X')">
                (<icon name="selected"/> <icon name="arrow"/> <icon name="exclude"/>)
                Mark Selected as Excluded
            </button>
        </div>
    </div>
</template>

<script>
import { data } from "../../../data";
import { applyDataToStore } from "../../../store/electronStore/applyDataToStore";

export default {
    name: 'quick-mark-dropdown',
    props: {
        filteredTasks: Object
    },
    data: () => ({
        dropdownOpen: false,
        lastChanged: []
    }),
    methods: {
        onChangeTaskCompletion: function(from, to) {
            this.lastChanged = [];

            let first = true;
            for(const id in this.filteredTasks) {
                const task = this.filteredTasks[id];

                if(from === '$' && task.selected || task.completionFlag === from) {
                    this.lastChanged.push({ task, oldFlag: task.completionFlag });

                    task.changeCompletionFlag(to, first);
                    first = false;
                }
            }

            applyDataToStore(data);
        },
        onUndoLastChange: function() {
            this.lastChanged.forEach((changed, index) => {
                changed.task.changeCompletionFlag(changed.oldFlag, index === 0);
            });
            applyDataToStore(data);
            this.lastChanged = [];
        }
    }
};
</script>

<style lang="scss">

</style>
