// src/app/core/component/task-table/cell/external/external-cell.component.ts
import { Component, Input } from '@angular/core';
import { shell } from '@electron/remote';

import { Task } from '@domain/Task';

@Component({
    selector: 'xiv-external-cell',
    templateUrl: './external-cell.component.html',
    styleUrls: ['./external-cell.component.scss']
})
export class ExternalCellComponent {
    @Input() task: Task;

    gotoGamerEscape() {
        let name = this.task.name.replace(/ /g, '_');
        name = gamerEscapeSafeMap(name);

        shell.openExternal(`https://ffxiv.gamerescape.com/wiki/${name}`);
    }

    gotoGarlandTools() {
        const name = this.task.name.replace(/ /g, '%20');
        shell.openExternal(`https://www.garlandtools.org/db/#search/${name}`);
    }
}

function gamerEscapeSafeMap(name) {
    const match = (n, id) => this.task.name === n && this.task.id === id;

    if(match('Mending Fences', 143)) return `${name}_(Levequest)`;

    return name;
}

// src/renderer/components/task-table/cell-types/ExternalCell.vue
<template>
    <td class="external-link-cell noSelect">
        <span
            title="Gamer Escape"
            @click="gotoGamerEscape()"
        >
            <img
                src="../../../assets/gamerescape.png"
                alt="Gamer Escape"
                height="20"
                width="20"
            >
        </span>
        <span
            title="Garland Tools"
            @click="gotoGarlandTools()"
        >
            <img
                src="../../../assets/Garland.png"
                alt="Garland Tools"
                height="20"
                width="20"
            >
        </span>
    </td>
</template>

<script>
    const { shell } = require('electron');

    export default {
        name: 'external-link-cell',
        props: {
            task: Object
        },
        methods: {
            gotoGamerEscape: function () {
                let name = this.task.name.replace(/ /g, '_');
                name = this.overrideForGamerEscape(name);

                shell.openExternal(`https://ffxiv.gamerescape.com/wiki/${name}`);
            },
            overrideForGamerEscape: function(name) {
                const match = (n, id) => this.task.name === n && this.task.id === id;

                if(match('Mending Fences', 143)) return `${name}_(Levequest)`

                return name;
            },
            gotoGarlandTools: function () {
                const name = this.task.name.replace(/ /g, '%20');
                shell.openExternal(`https://www.garlandtools.org/db/#search/${name}`);
            }
        }
    };
</script>

<style lang="scss">
.external-link-cell {
    width: 45px;

    .img {
        cursor: pointer;
    }
}
</style>
