// src/app/core/components/task-table/cell/numeric-complete/numeric-complete-cell.component.ts
import { Component, Input, OnChanges, SimpleChanges } from '@angular/core';

import { Task } from '../../../../../domain/Task';
import { rygGradient } from '../../../../../../styles/gradients';

import { StoreService } from '../../../../services/store/store.service';

@Component({
    selector: 'xiv-numeric-complete-cell',
    templateUrl: './numeric-complete-cell.component.html',
    styleUrls: ['./numeric-complete-cell.component.scss']
})
export class NumericCompleteCellComponent implements OnChanges {
    @Input() task: Task;
    @Input() value: string;

    step: number;
    tooltip: string;
    percentage: string;
    gradientBackground;

    constructor(private svcStore: StoreService) {
    }

    ngOnChanges(changes: SimpleChanges) {
        if(changes.task) {
            this.step = this._step;
            this.tooltip = this._tooltip;
            this.percentage = this._percentage;
            this.gradientBackground = this._gradientBackground;
        }
    }

    get _step() {
        return 1 / (10 ** this.task._parent.numericDecimal);
    }

    get _tooltip() {
        return `${this.task.minValue} - ${this.task.maxValue}`;
    }

    get _percentage() {
        const totProg = this.task.maxValue - this.task.minValue;
        let prog = parseFloat(this.value) - this.task.minValue;
        if(prog < 0) prog = 0;

        return ((prog / totProg) * 100).toFixed(2);
    }

    get _gradientBackground() {
        const prog = parseInt(this.value, 10) - this.task.minValue;
        const tot = this.task.maxValue - this.task.minValue;

        return rygGradient(prog / tot);
    }

    onTaskValueChange(event) {
        let newValue = parseFloat(event.target.value || this.task.minValue);
        newValue = parseFloat(newValue.toFixed(this.task._parent.numericDecimal));

        // Validate the new value
        if(newValue < this.task.minValue) newValue = this.task.minValue;
        if(newValue > this.task.maxValue) newValue = this.task.maxValue;

        // Update the new value
        this.task.changeCompletionNumber(newValue, true);
        this.svcStore.pStore.set(this.task.fullStorageKey, newValue.toString());

        // Force validation changes to update the UI
        //TODO this.$forceUpdate();
    }
}

// src/renderer/components/task-table/cell-types/NumericCompleteCell.vue
<template>
    <td class="completion-flag-cell noSelect" :style="gradientBackground" :title="tooltip">
        <input
            class="numeric-input"
            type="number"
            :step="step"
            :value="value"
            @blur="onTaskValueChange($event)"
        />
        <span class="percentage">{{percentage}}%</span>
    </td>
</template>

<script>
    import { getPlayerStore } from "../../../../store/electronStore";
    import { rygGradient } from "../../../../styles/gradients";

    export default {
        name: 'completion-number-cell',
        props: {
            task: Object,
            value: String,
        },
        computed: {
            step: function() {
                return 1 / (10 ** this.task._parent.numericDecimal);
            },
            gradientBackground: function() {
                const prog = parseInt(this.value) - parseInt(this.task.minValue);
                const tot = parseInt(this.task.maxValue) - parseInt(this.task.minValue);

                return rygGradient(prog / tot);
            },
            percentage: function() {
                const totProg = this.task.maxValue - this.task.minValue;
                let prog = parseFloat(this.value) - this.task.minValue;
                if(prog < 0) prog = 0;

                return ((prog / totProg) * 100).toFixed(2);
            },
            tooltip: function() {
                return `${this.task.minValue} - ${this.task.maxValue}`;
            }
        },
        methods: {
            onTaskValueChange: function(event) {
                let newValue = parseFloat(event.target.value || this.task.minValue).toFixed(this.task._parent.numericDecimal);

                // Validate the new value
                if(newValue < this.task.minValue) newValue = this.task.minValue;
                if(newValue > this.task.maxValue) newValue = this.task.maxValue;

                // Update the new value
                this.task.changeCompletionNumber(newValue);
                getPlayerStore().set(this.task.fullStorageKey, newValue.toString());

                // Force validation changes to update the UI
                this.$forceUpdate();
            }
        }
    };
</script>

<style lang="scss">
@import '../../../../styles/colors';

.completion-flag-cell {
    border: 1px solid transparent;
    color: black;
    cursor: pointer;
    text-align: center;
    user-select: none;
    width: 99px;

    &:hover {
        border: 1px solid white;
    }

    .numeric-input {
        background-color: transparent;
        border: none;
        border-bottom: 1px solid;
        color: $blue-1;
        margin: 5px 2.5% 10px 2.5%;
        width: 95%;
    }

    .percentage {
        color: $blue-1;
        float: right;
        font-size: 8pt;
        margin-top: -8px;
    }
}
</style>
