// src/app/core/components/task-table/task-table.component.ts
import { Component, ElementRef, Input, OnChanges, SimpleChanges, ViewChild } from '@angular/core';

import { DataGroup } from '../../../domain/DataGroup';
import { Task } from '../../../domain/Task';

import { StoreService } from '../../services/store/store.service';

@Component({
    selector: 'xiv-task-table',
    templateUrl: 'task-table.component.html',
    styleUrls: ['./task-table.component.scss']
})
export class TaskTableComponent implements OnChanges {
    @Input() columnConfig: any[];
    @Input() group: DataGroup;
    @Input() tasks: { [key: string]: Task };
    @ViewChild('taskTable') taskTableRef: ElementRef;

    displayedTasks = 0;
    totalTasks = 0;
    rerenderKey = 0;

    hasTasks: boolean;
    uniqueValues: any;
    filteredTasks: { [key: string]: Task };

    filters = {
        completion: {}
    };

    constructor(private svcStore: StoreService) {
        this.filters.completion = this.svcStore.eStore.get('table-filters');
    }

    ngOnChanges(changes: SimpleChanges) {
        const { columnConfig, group, tasks } = changes;

        if(group) {
            const isValidGroupChange = group.currentValue && group.previousValue.name !== group.currentValue.name;

            if(isValidGroupChange && this.taskTableRef) {
                this.taskTableRef.nativeElement.scrollTop = 0;
            }
        }

        if(tasks) this.hasTasks = this._hasTasks;

        if(columnConfig || group || tasks) {
            this.uniqueValues = this._uniqueValues;
            this.filteredTasks = this._filteredTasks;
        }
    }

    onFilterChange(filters) {
        this.filters = filters;
    }

    onSelectChange() {
        this.rerenderKey++;
    }

    //#region----------------------------------------------------------- Computed
    get _hasTasks() {
        return this.tasks && Object.keys(this.tasks).length > 0;
    }

    get _uniqueValues() {
        const uniqueValues = {};

        // Grab unique values from the filtered task list
        for(const id in this.filteredTasks) {
            if(this.filteredTasks.hasOwnProperty(id)) {
                const task = this.filteredTasks[id];

                this.columnConfig.forEach(({ key }) => {
                    if(!uniqueValues[key]) uniqueValues[key] = [];

                    const value = !task[key] && task[key] !== 0 ? '' : task[key];
                    if(uniqueValues[key].indexOf(value) === -1) {
                        uniqueValues[key].push(value);
                    }
                });
            }
        }

        // Sort the unique values for pretty filter dropdowns
        this.columnConfig.forEach((column) => {
            if(!uniqueValues[column.key]) return;
            if(column.filterType === 'number') {
                uniqueValues[column.key].sort((a, b) => parseInt(a, 10) - parseInt(b, 10));
            }
            else {
                uniqueValues[column.key].sort();
            }
        });

        return uniqueValues;
    }

    get _filteredTasks() {
        const filtered = Object.assign({}, this.tasks);
        const hotwire = this.group.isNumericCompletion ? [] : [{ key: 'completion' }];
        hotwire.push(...this.columnConfig);

        for(const { key } of hotwire) {
            const filter = this.filters[key];

            if(filter) {
                for(const id in filtered) {
                    if(filtered.hasOwnProperty(id)) {
                        let removeFromFiltered = false;

                        // Completion filters
                        if(key === 'completion') {
                            switch(this.tasks[id].completionFlag) {
                                case 'Y': removeFromFiltered = !filter.completed; break;
                                case 'N': removeFromFiltered = !filter.incomplete; break;
                                case 'X': removeFromFiltered = !filter.excluded; break;
                                default: removeFromFiltered = !filter.incomplete; break;
                            }
                        }
                        // Blank value search
                        else if(filter.value === 'Blank') {
                            removeFromFiltered = !!filtered[id][key];
                        }
                        // Column value fuzzy search filter
                        else {
                            let safeValue = filtered[id][key];
                            if(safeValue === null || safeValue === undefined) safeValue = '';

                            const columnValue = safeValue.toString().toLowerCase();
                            removeFromFiltered = !columnValue.includes(filter.value.toLowerCase());
                        }

                        if(removeFromFiltered) {
                            delete filtered[id];
                        }
                    }
                }
            }
        }

        this.displayedTasks = Object.keys(filtered).length;
        this.totalTasks = Object.keys(this.tasks).length;

        return filtered;
    }

    //#endregion
}

<div *ngIf="!!columnConfig" class="task-table-container">
    <div class="task-table-toolbar">
        <span *ngIf="hasTasks && !group.isNumericCompletion">
            <xiv-quick-mark-dropdown
                [filteredTasks]="filteredTasks"
            ></xiv-quick-mark-dropdown>
        </span>

        <span *ngIf="hasTasks && !group.isNumericCompletion">
            <xiv-select-dropdown
                [group]="group"
                [filteredTasks]="filteredTasks"
                (selectChange)="onSelectChange()"
            ></xiv-select-dropdown>
        </span>

        <span *ngIf="hasTasks">
            <xiv-chain-dropdown
                [disableUndo]="group.isCustomGroup"
            ></xiv-chain-dropdown>
        </span>

        <span *ngIf="group.isCustomGroup">
            <xiv-custom-task-dropdown
                [filteredTasks]="filteredTasks"
            ></xiv-custom-task-dropdown>
        </span>

        <span
            *ngIf="hasTasks"
            class="row-count"
            [title]="(totalTasks - displayedTasks) + ' Hidden'"
        >
            {{displayedTasks}} Rows displayed
        </span>
    </div>

    <div class="task-table-scroll-container" #taskTable>
        <table class="xiv-table" *ngIf="hasTasks">
            <xiv-header-row
                (filterChange)="onFilterChange($event)"
                [columnConfig]="columnConfig"
                [uniqueValues]="uniqueValues"
                [isNumericCompletion]="group.isNumericCompletion"
            ></xiv-header-row>
            <xiv-data-row
                [columnConfig]="columnConfig"
                [enableDrag]="group.draggable"
                [tasks]="filteredTasks"
            ></xiv-data-row>
        </table>
    </div>
</div>

// src/renderer/main-content/task-table/TaskTable.vue
<template>
    <div id="item-container" v-if="!!columnConfig">
        <span v-if="hasTasks && !tasks[0].isNumericCompletion">
            <quick-mark-dropdown
                v-on:select-change="onSelectChange"
                :filtered-tasks="filteredTasks"
            />
        </span>

        <span v-if="group.isCustomGroup">
            <add-custom-task
                :filtered-tasks="filteredTasks"
            />
        </span>

        <table class="task-table" v-if="hasTasks">
            <task-table-header
                @filter-change="onFilterChange"
                :column-config="columnConfig"
                :uniqueValues="uniqueValues"
                :is-numeric-completion="tasks[0].isNumericCompletion"
            />
            <task-table-data-row
                :key="rerenderKey"
                :column-config="columnConfig"
                :tasks="filteredTasks"
            />
        </table>
    </div>
</template>

<script>
    // Components
    import QuickMarkDropdown from './QuickMarkDropdown';
    import AddCustomTask from './AddCustomTask';
    import TaskTableHeader from './row-types/TaskTableHeader';
    import TaskTableDataRow from './row-types/TaskTableDataRow';

    // Export component
    export default {
        name: 'task-table',
        components: {
            'quick-mark-dropdown': QuickMarkDropdown,
            'add-custom-task': AddCustomTask,
            'task-table-header': TaskTableHeader,
            'task-table-data-row': TaskTableDataRow,
        },
        props: {
            columnConfig: Array,
            group: Object,
            tasks: Array,
        },
        data: () => ({
            filters: {},
            rerenderKey: 0
        }),
        computed: {
            hasTasks: function() {
                return this.tasks && this.tasks.length > 0;
            },
            uniqueValues: function() {
                const uniqueValues = {};

                // Grab unique values from the filtered task list
                this.filteredTasks.forEach((task) => {
                    this.columnConfig.forEach(({ key }) => {
                        if(!uniqueValues[key]) uniqueValues[key] = [];

                        if(task[key] && uniqueValues[key].indexOf(task[key]) === -1) {
                            uniqueValues[key].push(task[key]);
                        }
                    });
                });

                // Sort the unique values for pretty filter dropdowns
                this.columnConfig.forEach((column) => {
                    if(!uniqueValues[column.key]) return;
                    if(column.filterType === 'number') {
                        uniqueValues[column.key].sort((a, b) => parseInt(a) - parseInt(b));
                    }
                    else {
                        uniqueValues[column.key].sort();
                    }
                });

                return uniqueValues;
            },
            filteredTasks: function() {
                let filtered = this.tasks.concat();

                if(this.filters.completed) {
                    filtered = filtered.filter((task) => {
                        const completed = task.completionFlag;
                        const filterCompleted = this.filters.completed.value;

                        if(!completed && filterCompleted === 'N') return true;
                        return completed === filterCompleted;
                    });
                }

                for(let i = 0; i < this.columnConfig.length; i++) {
                    const key = this.columnConfig[i].key;
                    const filter = this.filters[key];

                    if(filter) {
                        if(filter.filterType === 'search') {
                            filtered = filtered.filter((task) =>
                                task[key].toString().toLowerCase().includes(filter.value.toLowerCase())
                            );
                        }
                        else {
                            filtered = filtered.filter((task) =>
                                task[key] === filter.value
                            );
                        }
                    }
                }

                return filtered;
            }
        },
        methods: {
            onFilterChange: function(filters) {
                this.filters = filters;
            },
            onSelectChange: function() {
                this.rerenderKey++;
            },
            addCustomTask: function() {

            }
        }
    }
</script>

<style>
    /*---------------------- Container ----------------------*/
    #item-container {

    }

    #item-container > span {
        display: inline-block;
    }

    .task-table {
        border-spacing: 0;
        width: 100%;
    }

    /*---------------------- Row ----------------------*/
    .task-table tr {
        background-color: #3282B8;
        border-bottom: 1px solid black;
        cursor: pointer;
    }

    .task-table tr:nth-child(even) {
        background-color: #0F4C75;
    }
</style>
