// src/app/view/main-content/main-content.component.ts
import { Component, OnInit } from '@angular/core';

import { DataGroup } from '@domain/DataGroup';
import { NavigationService } from '@service/navigation/navigation.service';

@Component({
    selector: 'xiv-main-content',
    templateUrl: './main-content.component.html',
    styleUrls: ['./main-content.component.scss']
})
export class MainContentComponent implements OnInit {
    //TODO: allData: data
    selectedGroup: DataGroup;
    showAll: boolean = false;
    isShowAllVisible: boolean = false;

    constructor(private svcNavigation: NavigationService) {
    }

    ngOnInit(): void {
        this.svcNavigation.selectedGroup$.subscribe((selectedGroup) => {
            this.selectedGroup = selectedGroup;
            this.showAll = false;
            this.isShowAllVisible = !!selectedGroup?.subGroups?.columnConfig;
        });
    }

    toggleShowAll() {
        this.showAll = !this.showAll;
    }
}

<div id="main-content" *ngIf="!!selectedGroup">
    <!----------- Landing Page / Fallback ----------->
    <div *ngIf="selectedGroup.noContent || !selectedGroup; else customGroup">
        <xiv-landing-page></xiv-landing-page>
    </div>

    <!----------- Custom Component Group ----------->
    <ng-template #customGroup>
        <div
            *ngIf="selectedGroup.component; else textGroup"
            class="custom-group-component"
        >
            <ng-template anchor></ng-template>
        </div>
    </ng-template>

    <ng-template #textGroup>
        <span *ngIf="selectedGroup.text; else tableGroup">
            {{selectedGroup.text}}
        </span>
    </ng-template>

    <!----------- Summary & Task Table ----------->
    <ng-template #tableGroup>
        <ng-template *ngIf="!showAll">
            <div *ngIf="selectedGroup.subGroups" class="group-summary-section">
                <xiv-summary-line
                    *ngFor="let subGroup of selectedGroup.subGroups"
                    [group]="subGroup"
                ></xiv-summary-line>
            </div>

            <div class="section-actions" *ngIf="isShowAllVisible">
                <button
                    class="xiv-button"
                    (click)="toggleShowAll()"
                >
                    {{showAll ? 'Hide All Tasks' : 'Show All Tasks'}}
                </button>
            </div>
        </ng-template>

        <ng-template *ngIf="showAll">
            <div class="section-actions">
                <button
                    class="xiv-button exit-all-button"
                    (click)="toggleShowAll()"
                >
                    Exit All Task View
                </button>
            </div>
        </ng-template>

        <!----------- Task Tables (show all & base) ----------->
        <ng-template *ngIf="isShowAllVisible && showAll; else baseTable">
            <xiv-show-all-section [group]="selectedGroup"></xiv-show-all-section>
        </ng-template>

        <ng-template #baseTable>
            <xiv-task-table
                *ngIf="selectedGroup.taskCount !== null"
                [group]="selectedGroup"
                [columnConfig]="selectedGroup.columnConfig"
                [tasks]="selectedGroup.tasks"
            ></xiv-task-table>
        </ng-template>
    </ng-template>
</div>

<!--<div class="container">-->
<!--    <h1 class="title">-->
<!--        {{ 'PAGES.HOME.TITLE' | translate }}-->
<!--    </h1>-->

<!--    <a routerLink="/detail">{{ 'PAGES.HOME.GO_TO_DETAIL' | translate }}</a>-->
<!--</div>-->

// src/renderer/main-content/MainContent.vue
<template>
    <div id="main-content" v-if="!!selectedGroup">
        <!----------- Top-Level Summary ----------->
        <div v-if="selectedGroup.noContent || !selectedGroup">
            <landing-page/>
        </div>
        <!----------- Selected Custom Component ----------->
        <template v-else-if="selectedGroup.component">
            <component v-bind:is="selectedGroup.component"></component>
        </template>
        <template v-else-if="selectedGroup.text">
            {{selectedGroup.text}}
        </template>
        <!----------- Summary & Task Table ----------->
        <template v-else>
            <template v-if="!showAll">
                <div v-if="selectedGroup.subGroups" class="group-summary-section">
                    <summary-line
                        v-for="subGroup in selectedGroup.subGroups"
                        :key="subGroup.name"
                        :group="subGroup"
                    />
                </div>

                <div class="section-actions">
                    <button
                        class="xiv-button"
                        v-if="showShowAllButton"
                        @click="toggleShowAll"
                    >
                        {{showAll ? 'Hide All Tasks' : 'Show All Tasks'}}
                    </button>
                </div>
            </template>
            <template v-else>
                <button
                    class="xiv-button exit-all-button"
                    @click="toggleShowAll"
                >
                    Exit All Task View
                </button>
            </template>

            <!----------- Task Tables (base & show all) ----------->
            <template v-if="showShowAllButton && showAll">
                <show-all-section :group="selectedGroup" />
            </template>
            <template v-else-if="selectedGroup.taskCount !== null">
                <task-table
                    :group="selectedGroup"
                    :column-config="selectedGroup.columnConfig"
                    :tasks="selectedGroup.tasks"
                />
            </template>
        </template>
    </div>
</template>

<script>
    import { mapState } from "vuex";

    import { data } from '../../data';
    import LandingPage from '../pages/landing-page';
    import SummaryLine from '../components/SummaryLine';
    import SearchData from '../pages/search-data/SearchData';
    import ShowAllSection from "./ShowAllSection";
    import TaskTable from '../components/task-table/TaskTable';

    export default {
        name: 'main-content',
        data: () => ({
            allData: data,
            showAll: false,
        }),
        components: {
            'landing-page': LandingPage,
            'summary-line': SummaryLine,
            'search-data': SearchData,
            'show-all-section': ShowAllSection,
            'task-table': TaskTable,
        },
        computed: {
            ...mapState('navigation', {
                selectedGroup: 'selectedGroup',
            }),
            showShowAllButton: function() {
                return (this.selectedGroup && this.selectedGroup.subGroups && this.selectedGroup.columnConfig);
            },
        },
        watch: {
            selectedGroup: function(oldGroup, newGroup) {
                if(!oldGroup || !newGroup) return;

                if(oldGroup.name !== newGroup.name) this.showAll = false;
            }
        },
        methods: {
            toggleShowAll: function() {
                this.showAll = !this.showAll;
            }
        }
    };
</script>

<style lang="scss">
@import '../../styles/colors';

#main-content {
    height: calc(100% - 160px);
    margin: 10px;

    .group-summary-section {
        display: flex;
        flex-wrap: wrap;
    }

    .section-actions {
        text-align: center;
    }

    .exit-all-button {
        float: right;
        margin-right: 20px;
    }
}
</style>
